#+TITLE: Unix-Like Data Processing

Inspiration: [[http://atu15.onlineta.org/unix-like-data-processing.pdf][ATU
15]].

* Abstract

You might be familiar with such modern "Unix-like" operating systems as Linux,
FreeBSD, OpenBSD, OS X, iOS, etc. Underlying all, except perhaps the last
couple examples, is a programmer-friendly user experience philosophy: "Write
programs that do one thing and do it well. Write programs to work together.
Write programs to handle text streams, because that is a universal interface."
— Doug McIlroy.

The purpose of this informal summer course is to introduce to this philosphy of
using the computer. This philosophy is probably quite different from what you
are accustomed to, but puts great power at your fingertips. Most of the
problems we present, typically demand many lines of code in any concievable,
conventional programming language, even Python.

All you need to bring is a modern computer with a physical keyboard (not a
tablet).  We will provide access to a Linux machine directly via your web
browser.

* Contents
** Operating Systems
** Shell 101
** More Data For Your Shell
** Advanced Data Manipulation
** Structured Data Manipulation
** Plotting
